name: 'Containers Deployer'
description: 'A GitHub Action to deploy containers to Docker / Podman continuously.'

runs:
    using: 'docker'
    image: 'Dockerfile'

inputs:
    ssh_host:
        description: 'Hostname or IP address of the server where to deploy.'
        required: true

    ssh_port:
        description: 'Port number to SSH server.'
        required: false
        default: 22

    ssh_user:
        description: 'Username to work behalf of on the server.'
        required: true

    ssh_key:
        description: 'SSH identity key for authentication.'
        required: true
